#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $ac_adapt;
my $full_text;
my $short_text;
my $icon;
my $color;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "$percent%";
$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# consider color and urgent flag only on discharge
$icon = "︇";

if ($status eq 'Discharging') {

	if($percent < 15){
		$icon = "  ";
		$color = "#F44336";
	}elsif ($percent < 30) {
		$icon = "  ";
		$color = "#FFEB3B";
	} elsif ($percent < 60) {
		$icon = "  ";
		$color = "#8BC34A";
	} elsif ($percent < 90) {
		$icon = "  ";
		$color = "#4CAF50";
	} elsif ($percent > 90) {
		$icon = "  ";
		$color = "#2E7D32"; 
	}

}
$icon .= $full_text;
print "$icon\n"; 
print "#FF0000\n";

exit(0);
